exclude: '^v2/.*$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: 'CHANGELOG.md'
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix, --unsafe-fixes]
      - id: ruff-format

  # ty isn't passing yet
  # - repo: https://github.com/allganize/ty-pre-commit
  #   rev: v0.0.26
  #   hooks:
  #     - id: ty-check

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --exclude v2 .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: kacl-verify
        name: kacl-verify
        entry: uv run kacl-cli verify
        language: system
        files: 'CHANGELOG.md'
        pass_filenames: false
