FROM bg-scraper:latest

RUN mkdir --parents /app
WORKDIR /app

# Java 8 installation instructions: https://linuxize.com/post/install-java-on-debian-10/#installing-openjdk-8
RUN apt-get -y update && \
    apt-get -y install --no-install-recommends \
        software-properties-common && \
    wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
    add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ && \
    apt-get -y update && \
    apt-get -y install --no-install-recommends \
	    adoptopenjdk-8-hotspot && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64

ENTRYPOINT ["pipenv", "run"]
CMD ["scrapy", "list"]
